# Import library

In [229]:
import pandas as pd
import re
import numpy as np

#library that contains punctuation
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

# Import data

In [230]:
df=pd.read_csv('nhatot.csv')

In [231]:
df.columns

Index(['post_id', 'Loại tin', 'Tiêu đề', 'Giá', 'Diện tích', 'Địa chỉ',
       'Giá/m2', 'Giấy tờ pháp lý', 'Loại hình đất', 'Mô tả', 'URL', 'date',
       'Liên hệ', 'card_visit', 'Hướng cửa chính', 'Chiều ngang', 'Chiều dài',
       'Đặc điểm nhà/đất', 'Số phòng ngủ', 'Số phòng vệ sinh',
       'Loại hình nhà ở', 'Diện tích sử dụng', 'Tổng số tầng',
       'Tình trạng nội thất', 'Tên phân khu/Lô/Block/Tháp',
       'Tình trạng bất động sản', 'Tầng số', 'Hướng ban công',
       'Loại hình căn hộ', 'Loại hình văn phòng', 'Mã căn', 'Đặc điểm căn hộ',
       'Mã lô', 'Số tiền cọc'],
      dtype='object')

In [232]:
df.head()

post_id Loại tin                                            Tiêu đề  \
0  110154174  Mua bán  Bán 4ha đất vườn sổ đỏ có sẳn trang trại nhà v...   
1  102957944  Mua bán  Bán đất 21 Đỗ Nhuận, dt: 250m2, ngang 8m, nở h...   
2  108055434  Mua bán  Bán nhà hẻm 3m5 Nguyễn Văn Linh, 140m2 đất, ng...   
3  102942264  Mua bán  Bán đất hẻm 3m 59/31 Núi Thành, 162m2, 4.25 tỷ...   
4  110181789  Mua bán  Nhà 2 tầng 2 mặt kiệt ngay biển Nguyễn Tất Thà...   

       Giá  Diện tích                                            Địa chỉ  \
0   9,5 tỷ   40000 m²       DT 602, Xã Hòa Ninh, Huyện Hòa Vang, Đà Nẵng   
1   8,2 tỷ     250 m²  21, Đường Đỗ Nhuận, Phường Hòa Minh, Quận Liên...   
2  4,95 tỷ     140 m²  K82/H10/36, Nguyễn văn linh, Phường Nam Dương,...   
3  4,25 tỷ     162 m²  Kiệt 59 Núi Thành, Phường Bình Hiên, Quận Hải ...   
4  2,95 tỷ      62 m²  K1/20, Tôn Thất Đạm, Phường Xuân Hà, Quận Than...   

            Giá/m2 Giấy tờ pháp lý     Loại hình đất  \
0     237.500 đ/m²        Đã có sổ   Đất nông nghiệp   
1    32,8 triệu/m²        Đã có sổ        Đất thổ cư   
2   35,36 triệu/m²        Đã có sổ               NaN   
3   26,23 triệu/m²             NaN        Đất thổ cư   
4   47,58 triệu/m²        Đã có sổ               NaN   

                                               Mô tả  ...  \
0  💥💥💥Đất rộng lại giá tốt 40.000m có sẵn vườn câ...  ...   
1  + Bán đất số 21 Đỗ Nhuận, khu Trung Nghĩa, phư...  ...   
2  Bán nhà kiệt 82 Nguyễn Văn Linh, hẻm 3m5, cách...  ...   
3  Bán đất hẻm 3m số 59/31 Núi Thành, cách đường ...  ...   
4  Tôi là chính chủ cần bán nhà tại địa chỉ K1/20...  ...   

  Tên phân khu/Lô/Block/Tháp Tình trạng bất động sản Tầng số Hướng ban công  \
0                        NaN                     NaN     NaN            NaN   
1                        NaN                     NaN     NaN            NaN   
2                        NaN                     NaN     NaN            NaN   
3                        NaN                     NaN     NaN            NaN   
4                        NaN                     NaN     NaN            NaN   

  Loại hình căn hộ Loại hình văn phòng Mã căn Đặc điểm căn hộ Mã lô  \
0              NaN                 NaN    NaN             NaN   NaN   
1              NaN                 NaN    NaN             NaN   NaN   
2              NaN                 NaN    NaN             NaN   NaN   
3              NaN                 NaN    NaN             NaN   NaN   
4              NaN                 NaN    NaN             NaN   NaN   

  Số tiền cọc  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  

[5 rows x 34 columns]

In [233]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24285 entries, 0 to 24284
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   post_id                     24285 non-null  int64  
 1   Loại tin                    24285 non-null  object 
 2   Tiêu đề                     24285 non-null  object 
 3   Giá                         24285 non-null  object 
 4   Diện tích                   24285 non-null  object 
 5   Địa chỉ                     24285 non-null  object 
 6   Giá/m2                      12394 non-null  object 
 7   Giấy tờ pháp lý             12921 non-null  object 
 8   Loại hình đất               4937 non-null   object 
 9   Mô tả                       24285 non-null  object 
 10  URL                         24285 non-null  object 
 11  date                        24285 non-null  object 
 12  Liên hệ                     24267 non-null  object 
 13  card_visit                  242

In [234]:
df.shape

(24285, 34)

# Function

In [235]:
def replace_empty_with_nan(text):
    return np.nan if text.strip() == '' else text

# Loại tin

In [236]:
df['Loại tin'].unique()

array(['Mua bán', 'Cho thuê'], dtype=object)

# Diện tích

In [237]:
# df['Diện tích'].unique()

In [238]:
def clean_size(i):
    if isinstance(i, str):
        # Remove ' m²'
        return i.replace(' m²','').replace(' m2','')
    else:
        return ''

In [239]:
df['Diện tích'] = df['Diện tích'].apply(clean_size)

In [240]:
df['Diện tích'] = df['Diện tích'].apply(replace_empty_with_nan)

In [241]:
df['Diện tích']=df['Diện tích'].astype(float)

# Giá 

In [242]:
df['Giá'].unique()

array(['9,5 tỷ', '8,2 tỷ', '4,95 tỷ', ..., '6,199999999 tỷ', '200 tỷ',
       '1,279 tỷ'], dtype=object)

In [243]:
# df['Giá'][df['Loại tin']=='Mua bán'].unique()

In [244]:
# df['Giá'][df['Loại tin']=='Cho thuê'].unique()

In [245]:
df['Giá'] = df['Giá'].apply(lambda x: x.replace('.','').replace(',', '.'))

In [246]:
def clean_price(x, dien_tich):
    if 'đ/tháng' in x:
        return float(x.split()[0]) 
    elif 'triệu/tháng' in x:
        return float(x.split()[0]) * 1000000
    elif 'tỷ/tháng' in x:
        return float(x.split()[0]) * 1000000000
    elif ' tỷ' in x:
        return float(x.split()[0]) * 1000000000
    elif ' triệu' in x:
        return float(x.split()[0]) * 1000000
    elif ' đ' in x:
        return float(x.split()[0])
    elif x == 'Thỏa thuận':
        return None  
    else:
        return x

In [247]:
df['Giá'] = df.apply(lambda row: clean_price(row['Giá'], row['Diện tích']), axis=1)

In [248]:
df['Giá']=df['Giá'].astype(float)

# Giá/m2

In [249]:
df['Giá/m2'].unique()

array([' 237.500 đ/m²', ' 32,8 triệu/m²', ' 35,36 triệu/m²', ...,
       ' 62,57 triệu/m²', ' 58,17 triệu/m²', ' 20,08 triệu/m²'],
      dtype=object)

In [250]:
df['Giá/m2'] = df['Giá/m2'].apply(lambda x: str(x).replace('.', '').replace(',', '.').replace('m2','m²'))

In [251]:
def clean_price(x):
    if 'đ/m²' in x:
        return float(x.split()[0]) 
    elif 'triệu/m²' in x:
        return float(x.split()[0]) * 1000000
    elif 'tỷ/m²' in x:
        return float(x.split()[0]) * 1000000000
    elif x == 'Thỏa thuận':
        return None  
    else:
        return x

In [252]:
df['Giá/m2']=df['Giá/m2'].apply(clean_price)

In [253]:
df['Giá/m2']=df['Giá/m2'].astype(float)

# Giấy tờ pháp lý

In [254]:
df['Giấy tờ pháp lý'].unique()

array([' Đã có sổ', nan, ' Đang chờ sổ', ' Giấy tờ khác'], dtype=object)

In [255]:
df['Giấy tờ pháp lý']=df['Giấy tờ pháp lý'].str.strip()

# Loại hình đất, loại hình căn hộ, loại hình văn phòng, loại hình nhà ở

In [256]:
df['Loại hình đất'].unique()

array([' Đất nông nghiệp', ' Đất thổ cư', nan, ' Đất nền dự án',
       ' Đất công nghiệp'], dtype=object)

In [257]:
df['Loại hình căn hộ'].unique()

array([nan, ' Chung cư', ' Căn hộ dịch vụ, mini', ' Duplex', ' Officetel',
       ' Penthouse', ' Tập thể, cư xá'], dtype=object)

In [258]:
df['Loại hình văn phòng'].unique()

array([nan, ' Mặt bằng kinh doanh', ' Shophouse', ' Văn phòng',
       ' Officetel'], dtype=object)

In [259]:
df['Loại hình nhà ở'].unique()

array([nan, ' Nhà ngõ, hẻm', ' Nhà mặt phố, mặt tiền', ' Nhà biệt thự',
       ' Nhà phố liền kề'], dtype=object)

In [260]:
df['Loại hình đất']=df['Loại hình đất'].str.strip()
df['Loại hình căn hộ']=df['Loại hình căn hộ'].str.strip()
df['Loại hình văn phòng']=df['Loại hình văn phòng'].str.strip()
df['Loại hình nhà ở']=df['Loại hình nhà ở'].str.strip()

# date

In [261]:
df['date'].unique()

array(['2023-09-24', '2023-09-25', '2023-09-26', '2023-09-27',
       '2023-10-02', '2023-10-03', '2023-10-04', '2023-10-05',
       '2023-10-09', '2023-10-10', '2023-10-12', '2023-10-13',
       '2023-10-14', '2023-10-17', '2023-10-18', '2023-10-19',
       '2023-10-21', '2023-10-23', '2023-10-24', '2023-10-25',
       '2023-10-28', '2023-10-29', '2023-10-30', '2023-10-31',
       '2023-11-01', '2023-11-02', '2023-11-03'], dtype=object)

# Liên hệ

In [262]:
df['Liên hệ'].unique()

array(['Minh Phương Phát', 'Quốc Huỳnh', 'Anh Tân', ...,
       'Nguyễn Thị Xuân Tâm', 'Phạm Hữu Bình Định', 'Anonymous'],
      dtype=object)

In [263]:
df['Liên hệ']=df['Liên hệ'].str.title()

# Hướng cửa chính, hướng ban công

In [264]:
df['Hướng cửa chính'].unique()

array([nan, ' Tây Nam', ' Tây', ' Tây Bắc', ' Đông Bắc', ' Đông Nam',
       ' Bắc', ' Nam', ' Đông'], dtype=object)

In [265]:
df['Hướng ban công'].unique()

array([nan, ' Đông Bắc', ' Tây Bắc', ' Đông', ' Tây', ' Đông Nam',
       ' Tây Nam', ' Bắc', ' Nam'], dtype=object)

In [266]:
df['Hướng cửa chính']=df['Hướng cửa chính'].str.strip()
df['Hướng ban công']=df['Hướng ban công'].str.strip()

# Chiều ngang, chiều dài, diện tích sử dụng

In [267]:
df['Chiều ngang'].unique()

array([nan, ' 8 m', ' 7 m', ' 6 m', ' 17 m', ' 13 m', ' 5 m', ' 4 m',
       ' 15 m', ' 4.5 m', ' 6.2 m', ' 10 m', ' 5.5 m', ' 7.4 m',
       ' 7.33 m', ' 7.5 m', ' 23 m', ' 6.5 m', ' 3.5 m', ' 3.43 m',
       ' 5.97 m', ' 5.06 m', ' 24 m', ' 16 m', ' 12 m', ' 4.2 m',
       ' 6.3 m', ' 45 m', ' 53 m', ' 25 m', ' 5.3 m', ' 5.7 m', ' 54 m',
       ' 3 m', ' 100 m', ' 6.23 m', ' 4.8 m', ' 5.15 m', ' 44 m',
       ' 5.2 m', ' 14 m', ' 4.1 m', ' 4.67 m', ' 5.23 m', ' 3.56 m',
       ' 35 m', ' 5.1 m', ' 5.34 m', ' 6.7 m', ' 18 m', ' 5.08 m',
       ' 12.1 m', ' 6.15 m', ' 3.69 m', ' 4.4 m', ' 14.8 m', ' 4.42 m',
       ' 2 m', ' 9 m', ' 20 m', ' 22 m', ' 7.7 m', ' 18.5 m', ' 8.4 m',
       ' 200 m', ' 15.5 m', ' 65 m', ' 70 m', ' 535 m', ' 3.8 m',
       ' 5.65 m', ' 8.77 m', ' 5.4 m', ' 5.8 m', ' 4.74 m', ' 7.1 m',
       ' 6.74 m', ' 38 m', ' 94 m', ' 8.2 m', ' 4.46 m', ' 17.9 m',
       ' 17.7 m', ' 9.5 m', ' 4.9 m', ' 3.67 m', ' 12.5 m', ' 11 m',
       ' 11.5 m', ' 9.6 m', ' 4.6 m', '

In [268]:
df['Chiều dài'].unique()

array([nan, ' 26 m', ' 20 m', ' 4 m', ' 19 m', ' 29 m', ' 16 m', ' 15 m',
       ' 25 m', ' 20.3 m', ' 25.2 m', ' 17 m', ' 23 m', ' 10 m', ' 35 m',
       ' 18 m', ' 12 m', ' 15.3 m', ' 21 m', ' 18.7 m', ' 30 m',
       ' 11.51 m', ' 15.2 m', ' 7 m', ' 16.5 m', ' 14 m', ' 22 m',
       ' 17.7 m', ' 22.5 m', ' 9 m', ' 40 m', ' 24 m', ' 11 m', ' 27 m',
       ' 12.5 m', ' 99 m', ' 14.4 m', ' 8 m', ' 20.5 m', ' 15.51 m',
       ' 13 m', ' 23.2 m', ' 28 m', ' 18.1 m', ' 5.1 m', ' 19.8 m',
       ' 36 m', ' 14.8 m', ' 14.5 m', ' 10.5 m', ' 33.3 m', ' 25.5 m',
       ' 8.6 m', ' 19.5 m', ' 11.25 m', ' 13.2 m', ' 16.7 m', ' 18.6 m',
       ' 60 m', ' 17.18 m', ' 21.7 m', ' 21.8 m', ' 34 m', ' 57.25 m',
       ' 8.35 m', ' 13.5 m', ' 11.1 m', ' 20.8 m', ' 6 m', ' 16.9 m',
       ' 32 m', ' 68 m', ' 41 m', ' 24.5 m', ' 50 m', ' 200 m', ' 77 m',
       ' 26.5 m', ' 9.16 m', ' 17.5 m', ' 13.25 m', ' 10.2 m', ' 18.5 m',
       ' 28.2 m', ' 15.4 m', ' 32.5 m', ' 20.2 m', ' 23.5 m', ' 7.8 m',
      

In [269]:
df['Diện tích sử dụng'].unique()

array([nan, ' 110 m²', ' 130 m²', ' 150 m²', ' 175 m²', ' 225 m²',
       ' 180 m²', ' 545 m²', ' 280 m²', ' 170 m²', ' 61 m²', ' 116 m²',
       ' 81 m²', ' 208 m²', ' 85 m²', ' 80 m²', ' 75 m²', ' 160 m²',
       ' 3000 m²', ' 62 m²', ' 240 m²', ' 135 m²', ' 245 m²', ' 66 m²',
       ' 82 m²', ' 286 m²', ' 100 m²', ' 250 m²', ' 350 m²', ' 400 m²',
       ' 72 m²', ' 165 m²', ' 868 m²', ' 120 m²', ' 230 m²', ' 360 m²',
       ' 210 m²', ' 200 m²', ' 106 m²', ' 50 m²', ' 44 m²', ' 500 m²',
       ' 60 m²', ' 213 m²', ' 266 m²', ' 74.6 m²', ' 300 m²', ' 218 m²',
       ' 64 m²', ' 420 m²', ' 226 m²', ' 108 m²', ' 222 m²', ' 115 m²',
       ' 140 m²', ' 155 m²', ' 93.5 m²', ' 176 m²', ' 2300 m²', ' 264 m²',
       ' 441 m²', ' 261 m²', ' 260 m²', ' 364 m²', ' 65 m²', ' 123 m²',
       ' 54 m²', ' 126 m²', ' 90 m²', ' 70 m²', ' 114 m²', ' 145 m²',
       ' 103 m²', ' 84 m²', ' 435 m²', ' 220 m²', ' 254 m²', ' 484 m²',
       ' 416.9 m²', ' 202 m²', ' 51 m²', ' 197 m²', ' 87 m²', ' 69 m²',

In [270]:
df['Chiều ngang']=df['Chiều ngang'].apply(lambda x: float(str(x).split()[0]))
df['Chiều dài']=df['Chiều dài'].apply(lambda x: float(str(x).split()[0]))
df['Diện tích sử dụng']=df['Diện tích sử dụng'].apply(lambda x: float(str(x).split()[0]))

# Đặt điểm nhà/đất

In [271]:
df['Đặc điểm nhà/đất'].unique()

array([nan, ' Mặt tiền', ' Hẻm xe hơi', ' Nở hậu', ' Hẻm xe hơi,Nở hậu',
       ' Mặt tiền,Nở hậu', ' Hẻm xe hơi,Nở hậu,Mặt tiền',
       ' Nở hậu,Hẻm xe hơi', ' Mặt tiền,Hẻm xe hơi,Nở hậu',
       ' Mặt tiền,Nở hậu,Hẻm xe hơi', ' Hẻm xe hơi,Mặt tiền',
       ' Nở hậu,Mặt tiền', ' Mặt tiền,Hẻm xe hơi',
       ' Nở hậu,Mặt tiền,Hẻm xe hơi', ' 1', ' Hẻm xe hơi,Mặt tiền,Nở hậu',
       ' Nở hậu,Hẻm xe hơi,Mặt tiền'], dtype=object)

In [272]:
df['Đặc điểm nhà/đất']=df['Đặc điểm nhà/đất'].str.strip()

In [273]:
def replace_f(text):
    if isinstance(text, str):
        text = text.strip().lower()
        if ('hẻm xe hơi' in text) and ('nở hậu' in text) and ('mặt tiền' in text):
            return 'Mặt tiền, Hẻm xe hơi, Nở hậu'
        elif ('hẻm xe hơi' in text) and ('nở hậu' in text):
            return 'Hẻm xe hơi, Nở hậu'
        elif ('hẻm xe hơi' in text)  and ('mặt tiền' in text):
            return 'Mặt tiền, Hẻm xe hơi'
        elif ('nở hậu' in text) and ('mặt tiền' in text):
            return 'Mặt tiền, Nở hậu'
        elif ('hẻm xe hơi' in text):
            return 'Hẻm xe hơi'
        elif ('nở hậu' in text):
            return 'Nở hậu'
        elif ('mặt tiền' in text):
            return 'Mặt tiền'
        else:
            return text
    else:
        return text

In [274]:
df['Đặc điểm nhà/đất']=df['Đặc điểm nhà/đất'].apply(replace_f)

# Số phòng ngủ, Số phòng vệ sinh

In [275]:
df['Số phòng ngủ'].unique()

array([nan, ' 3 phòng', ' nhiều hơn 10 phòng', ' 5 phòng', ' 6 phòng',
       ' 1 phòng', ' 2 phòng', ' 4 phòng', ' 7 phòng', ' 8 phòng',
       ' 9 phòng', ' 10 phòng'], dtype=object)

In [276]:
df['Số phòng vệ sinh'].unique()

array([nan, ' 3 phòng', ' 2 phòng', ' Nhiều hơn 6 phòng', ' 6 phòng',
       ' 1 phòng', ' 4 phòng', ' 5 phòng'], dtype=object)

In [277]:
df['Số phòng ngủ']=df['Số phòng ngủ'].astype(str)
df['Số phòng ngủ'] = df['Số phòng ngủ'].apply(lambda x: re.search(r'\d+', x).group() if re.search(r'\d+', x) else None)

In [278]:
df['Số phòng vệ sinh']=df['Số phòng vệ sinh'].astype(str)
df['Số phòng vệ sinh'] = df['Số phòng vệ sinh'].apply(lambda x: re.search(r'\d+', x).group() if re.search(r'\d+', x) else None)

# Tổng số tầng, tầng số

In [279]:
df['Tổng số tầng'].unique()

array([ nan,   2.,   3.,   1.,   4.,   5.,  10.,   6.,   8.,   7.,  14.,
        11.,  35.,  15.,  22.,   9.,  20.,  33.,  23., 275.,  66., 153.])

In [280]:
df['Tầng số'].unique()

array([ nan,   9.,   2.,   8.,   6.,   7.,   4.,  34.,  23.,   3.,  18.,
        10.,  28.,  16.,  15.,  11.,  14.,   5.,  12.,  29.,  25.,   1.,
        20.,  17.,  31.,  27.,  26.,  30.,  13.,  19.,  21.,  22.,  36.,
        33.,  40.,  35.,  38.,  44.,  55.,  39.,  24., 810., 963.,  32.])

# Tình trạng nội thất, tình trạng bất động sản

In [281]:
df['Tình trạng nội thất'].unique()

array([nan, ' Nội thất cao cấp', ' Nội thất đầy đủ', ' Bàn giao thô',
       ' Nhà trống'], dtype=object)

In [282]:
df['Tình trạng nội thất']=df['Tình trạng nội thất'].str.strip()

In [283]:
df['Tình trạng nội thất']=df['Tình trạng nội thất'].apply(lambda x: str(x).replace('Nhà trống', 'Không nội thất'))

In [284]:
df['Tình trạng bất động sản'].unique()

array([nan, ' Chưa bàn giao', ' Đã bàn giao'], dtype=object)

In [285]:
df['Tình trạng bất động sản']=df['Tình trạng bất động sản'].str.strip()

# Mã căn, mã lô

In [286]:
df['Mã căn'].unique()

array([nan, ' 205', ' 9999', ' 8888', ' 1', ' 10', ' 12', ' 38',
       ' P2-16.13', ' V1', ' 0905271165', ' P2-07.08', ' 250', ' 05',
       ' 2903', ' 904', ' P2-13.16', ' P2-03.12', ' 1606', ' 2105',
       ' P2-07.12', ' 11', ' 2607', ' P103A09', ' P10515', ' 75', ' CT10',
       ' 407', ' 140', ' 608', ' 6B06', ' 616', ' DNPlaza3beds', ' 301',
       ' VL1', ' 03', ' 101', ' 27', ' 08', ' 02', ' 302', ' 401', ' 402',
       ' 114', ' 24', ' ABC', ' 20', ' 06', ' 15', ' 11CT02',
       ' 623 nguyen tat thanh', ' 4004', ' 04', ' A301', ' 202', ' 168',
       ' 01', ' 09', ' CT10-CH01.07', ' CTO2', ' CH-07-07', ' P208-07',
       ' 11A08', ' B3-21-11', ' 12A05', ' k218', ' 3', ' P21508', ' 4B',
       ' P1508', ' B2.50', ' 17', ' NNC0738', ' NNC0737', ' NNC0736',
       ' NNC0735', ' JH02', ' P210-02', ' P2-10.09', ' P2-09.08',
       ' TN0079', ' S14', ' 68', ' 2202', ' P2-08.05', ' 58', ' P2-16.20',
       ' 482', ' 698', ' 53', ' 14', ' P2-12B.8', ' 1596', ' P2-8.20',
       ' 03A

In [287]:
df['Mã lô'].unique()

array([nan, ' 1111', ' 8888', ' 27', ' 16', ' B2.124', ' B3.36',
       ' B2.134', ' B2.41', ' 12', ' 46', ' 168', ' 38', ' 18', ' 15',
       ' 90', ' 213', ' B2A-10', ' E', ' B1', ' 356', ' 47', ' 68',
       ' B2.88', ' NCL', ' 32', ' 48', ' 118', ' B5-15x', ' b1-1 -38',
       ' Can ban lo dat 5x25', ' 7', ' 33 36', ' 21 Khu B2 40', ' 53',
       ' 34-B2.3', ' 94', ' 1x', ' 1', ' 110', ' 59', ' 120', ' 1458',
       ' 702', ' 0983611388', ' 467', ' 15x', ' 43.42', ' 367', ' 35',
       ' 5', ' 764', ' B2.3.3', ' 37', ' 29', ' 93', ' 115', ' 354',
       ' K31 & 32', ' 395', ' 04', ' 1517', ' 233', ' 111', ' 79', ' 52'],
      dtype=object)

In [288]:
df['Mã căn']=df['Mã căn'].str.strip()
df['Mã lô']=df['Mã lô'].str.strip()

# Đặc điểm căn hộ

In [289]:
df['Đặc điểm căn hộ'].unique()

array([nan, ' Căn góc'], dtype=object)

In [290]:
df['Đặc điểm căn hộ']=df['Đặc điểm căn hộ'].str.strip()

# Số tiền cọc

In [291]:
# df['Số tiền cọc'].unique()

In [292]:
df['Số tiền cọc']=df['Số tiền cọc'].apply( lambda x: float(str(x).strip().replace('.','').split()[0]))

# Mô tả

In [293]:
df['Mô tả'].unique()

array(['💥💥💥Đất rộng lại giá tốt 40.000m có sẵn vườn cây ăn quả, đất có sẵn nhà tiền chế kiên cố khoảng 300m2,hàng rào lưới b40, đèn năng lượng bắt quanh vườn.\n💥💥💥Đường bê tông kiên cố\nTường rào cổng nhà xây sẵn đất 3 mặt tiền\n🌹🌹🌹Vị trí hoà ninh không quy hoạch\ncách ubnd cách chợ trường học chỉ 1km,cách Bà nà hills chỉ 4km\nDi chuyển về tttp Đà Nẵng chỉ có 15km\nHình ảnh thực tế của lô đất\nLH. *** Minh Phương Phát',
       '+ Bán đất số 21 Đỗ Nhuận, khu Trung Nghĩa, phường Hòa Minh, DTĐ: 250m². Đường 5m5 lề 3m, ô tô đậu thoải mái.\n\n+ Khu dân cư trí thức, yên tĩnh, phù hợp để làm nhà ở.\n\n+ Hướng Tây Nam.\n+ Ngân hàng hỗ trợ vay 6 tỷ.\n\nGiá bán: 8.2 tỷ, thương lượng.',
       'Bán nhà kiệt 82 Nguyễn Văn Linh, hẻm 3m5, cách đường Nguyễn Văn Linh khoảng 100 m.\nVị trí đẹp ngay trung tâm thành phố. DTĐ: 140m², Chiều ngang 7m, DTSD: 110m². Lô đất rất giá trị, rất khó tìm lô đất tương tự ở ngay trung tâm thành phố!\n\nNhà gồm 3PN, 3WC, nhà đẹp, sạch sẽ. Hướng chính Tây.\n\nGiá: 4.95 

# Rename columns

In [294]:
df.columns

Index(['post_id', 'Loại tin', 'Tiêu đề', 'Giá', 'Diện tích', 'Địa chỉ',
       'Giá/m2', 'Giấy tờ pháp lý', 'Loại hình đất', 'Mô tả', 'URL', 'date',
       'Liên hệ', 'card_visit', 'Hướng cửa chính', 'Chiều ngang', 'Chiều dài',
       'Đặc điểm nhà/đất', 'Số phòng ngủ', 'Số phòng vệ sinh',
       'Loại hình nhà ở', 'Diện tích sử dụng', 'Tổng số tầng',
       'Tình trạng nội thất', 'Tên phân khu/Lô/Block/Tháp',
       'Tình trạng bất động sản', 'Tầng số', 'Hướng ban công',
       'Loại hình căn hộ', 'Loại hình văn phòng', 'Mã căn', 'Đặc điểm căn hộ',
       'Mã lô', 'Số tiền cọc'],
      dtype='object')

In [295]:
df=df.rename(columns={'Giấy tờ pháp lý':'Pháp lý','Liên hệ':'Tên người dùng','date':'Ngày crawl',
                      'Tình trạng nội thất':'Nội thất','Số phòng vệ sinh':'Số toilet','Hướng cửa chính':'Hướng nhà'})

# Save data

In [296]:
df

post_id  Loại tin                                            Tiêu đề  \
0      110154174   Mua bán  Bán 4ha đất vườn sổ đỏ có sẳn trang trại nhà v...   
1      102957944   Mua bán  Bán đất 21 Đỗ Nhuận, dt: 250m2, ngang 8m, nở h...   
2      108055434   Mua bán  Bán nhà hẻm 3m5 Nguyễn Văn Linh, 140m2 đất, ng...   
3      102942264   Mua bán  Bán đất hẻm 3m 59/31 Núi Thành, 162m2, 4.25 tỷ...   
4      110181789   Mua bán  Nhà 2 tầng 2 mặt kiệt ngay biển Nguyễn Tất Thà...   
...          ...       ...                                                ...   
24280  111135665  Cho thuê       Cho thuê nhà 2 tầng mặt tiền nội thất cơ bản   
24281  111286550  Cho thuê  CHO THUÊ CĂN HỘ MONARCHY B 2PN TẦNG CAO CÓ VÀ ...   
24282  111364385  Cho thuê  CĂN STUDIO XINH XINH - GIẶT RIÊNG - NGAY HỒ XU...   
24283  111137370  Cho thuê             CĂN HỘ STUDIO FULL NỘI THẤT - HÒA XUÂN   
24284  110674866  Cho thuê   CĂN HỘ 1PN - FULL NỘI THẤT - TRUNG TÂM THÀNH PHỐ   

                Giá  Diện tích  \
0      9.500000e+09    40000.0   
1      8.200000e+09      250.0   
2      4.950000e+09      140.0   
3      4.250000e+09      162.0   
4      2.950000e+09       62.0   
...             ...        ...   
24280  7.000000e+06       90.0   
24281  1.000000e+07       80.0   
24282  5.300000e+06       38.0   
24283  3.200000e+06       25.0   
24284  6.200000e+06       35.0   

                                                 Địa chỉ      Giá/m2  \
0           DT 602, Xã Hòa Ninh, Huyện Hòa Vang, Đà Nẵng    237500.0   
1      21, Đường Đỗ Nhuận, Phường Hòa Minh, Quận Liên...  32800000.0   
2      K82/H10/36, Nguyễn văn linh, Phường Nam Dương,...  35360000.0   
3      Kiệt 59 Núi Thành, Phường Bình Hiên, Quận Hải ...  26230000.0   
4      K1/20, Tôn Thất Đạm, Phường Xuân Hà, Quận Than...  47580000.0   
...                                                  ...         ...   
24280  Trần Tấn Mới, Phường Hải Châu II, Quận Hải Châ...         NaN   
24281  An Trung 2, Phường An Hải Tây, Quận Sơn Trà, Đ...         NaN   
24282  Đường Khuê Mỹ Đông 5, Phường Khuê Mỹ, Quận Ngũ...         NaN   
24283  29 tháng 3, Phường Hòa Xuân, Quận Cẩm Lệ, Đà Nẵng         NaN   
24284  Nguyễn Thị Minh Khai, Phường Hải Châu  I, Quận...         NaN   

           Pháp lý    Loại hình đất  \
0         Đã có sổ  Đất nông nghiệp   
1         Đã có sổ       Đất thổ cư   
2         Đã có sổ              NaN   
3              NaN       Đất thổ cư   
4         Đã có sổ              NaN   
...            ...              ...   
24280          NaN              NaN   
24281  Đang chờ sổ              NaN   
24282          NaN              NaN   
24283          NaN              NaN   
24284          NaN              NaN   

                                                   Mô tả  ...  \
0      💥💥💥Đất rộng lại giá tốt 40.000m có sẵn vườn câ...  ...   
1      + Bán đất số 21 Đỗ Nhuận, khu Trung Nghĩa, phư...  ...   
2      Bán nhà kiệt 82 Nguyễn Văn Linh, hẻm 3m5, cách...  ...   
3      Bán đất hẻm 3m số 59/31 Núi Thành, cách đường ...  ...   
4      Tôi là chính chủ cần bán nhà tại địa chỉ K1/20...  ...   
...                                                  ...  ...   
24280  Cho thuê nhà mặt tiền đường 5m5 quận Hải Châu ...  ...   
24281  Cho thuê căn hộ Monarchy B.\n- Căn hộ 2PN full...  ...   
24282  🍀CHO THUÊ CĂN STUDIO XINH XINH - NGAY HỒ XUÂN ...  ...   
24283  - Vị trí: Đường 29/3 Hòa Xuân, gần đại học Kiế...  ...   
24284  - Vị trí: Đường Nguyễn Thị Minh Khai, gần trục...  ...   

      Tên phân khu/Lô/Block/Tháp Tình trạng bất động sản Tầng số  \
0                            NaN                     NaN     NaN   
1                            NaN                     NaN     NaN   
2                            NaN                     NaN     NaN   
3                            NaN                     NaN     NaN   
4                            NaN                     NaN     NaN   
...                          ...                     ...     ...   
24280                        NaN    

In [297]:
# df.to_excel('nt.xlsx')
# df.to_csv('nt.csv')