# Import library

In [1]:
import pandas as pd
import re
import numpy as np

#library that contains punctuation
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

# Import data

In [2]:
df=pd.read_csv('nhatot.csv')

In [3]:
df.columns

Index(['post_id', 'Loại tin', 'Tiêu đề', 'Giá', 'Diện tích', 'Địa chỉ',
       'Giá/m2', 'Giấy tờ pháp lý', 'Loại hình đất', 'Mô tả', 'URL', 'date',
       'Liên hệ', 'card_visit', 'Hướng cửa chính', 'Chiều ngang', 'Chiều dài',
       'Đặc điểm nhà/đất', 'Số phòng ngủ', 'Số phòng vệ sinh',
       'Loại hình nhà ở', 'Diện tích sử dụng', 'Tổng số tầng',
       'Tình trạng nội thất', 'Tên phân khu/Lô/Block/Tháp',
       'Tình trạng bất động sản', 'Tầng số', 'Hướng ban công',
       'Loại hình căn hộ', 'Loại hình văn phòng', 'Mã căn', 'Đặc điểm căn hộ',
       'Mã lô', 'Số tiền cọc'],
      dtype='object')

In [75]:
df.head()

post_id Loại tin                                            Tiêu đề  \
0  110154174  Mua bán  Bán 4ha đất vườn sổ đỏ có sẳn trang trại nhà v...   
1  102957944  Mua bán  Bán đất 21 Đỗ Nhuận, dt: 250m2, ngang 8m, nở h...   
2  108055434  Mua bán  Bán nhà hẻm 3m5 Nguyễn Văn Linh, 140m2 đất, ng...   
3  102942264  Mua bán  Bán đất hẻm 3m 59/31 Núi Thành, 162m2, 4.25 tỷ...   
4  110181789  Mua bán  Nhà 2 tầng 2 mặt kiệt ngay biển Nguyễn Tất Thà...   

       Giá  Diện tích                                            Địa chỉ  \
0   9,5 tỷ   40000 m²       DT 602, Xã Hòa Ninh, Huyện Hòa Vang, Đà Nẵng   
1   8,2 tỷ     250 m²  21, Đường Đỗ Nhuận, Phường Hòa Minh, Quận Liên...   
2  4,95 tỷ     140 m²  K82/H10/36, Nguyễn văn linh, Phường Nam Dương,...   
3  4,25 tỷ     162 m²  Kiệt 59 Núi Thành, Phường Bình Hiên, Quận Hải ...   
4  2,95 tỷ      62 m²  K1/20, Tôn Thất Đạm, Phường Xuân Hà, Quận Than...   

            Giá/m2 Giấy tờ pháp lý     Loại hình đất  \
0     237.500 đ/m²        Đã có sổ   Đất nông nghiệp   
1    32,8 triệu/m²        Đã có sổ        Đất thổ cư   
2   35,36 triệu/m²        Đã có sổ               NaN   
3   26,23 triệu/m²             NaN        Đất thổ cư   
4   47,58 triệu/m²        Đã có sổ               NaN   

                                               Mô tả  ...  \
0  💥💥💥Đất rộng lại giá tốt 40.000m có sẵn vườn câ...  ...   
1  + Bán đất số 21 Đỗ Nhuận, khu Trung Nghĩa, phư...  ...   
2  Bán nhà kiệt 82 Nguyễn Văn Linh, hẻm 3m5, cách...  ...   
3  Bán đất hẻm 3m số 59/31 Núi Thành, cách đường ...  ...   
4  Tôi là chính chủ cần bán nhà tại địa chỉ K1/20...  ...   

  Tên phân khu/Lô/Block/Tháp Tình trạng bất động sản Tầng số Hướng ban công  \
0                        NaN                     NaN     NaN            NaN   
1                        NaN                     NaN     NaN            NaN   
2                        NaN                     NaN     NaN            NaN   
3                        NaN                     NaN     NaN            NaN   
4                        NaN                     NaN     NaN            NaN   

  Loại hình căn hộ Loại hình văn phòng Mã căn Đặc điểm căn hộ Mã lô  \
0              NaN                 NaN    NaN             NaN   NaN   
1              NaN                 NaN    NaN             NaN   NaN   
2              NaN                 NaN    NaN             NaN   NaN   
3              NaN                 NaN    NaN             NaN   NaN   
4              NaN                 NaN    NaN             NaN   NaN   

  Số tiền cọc  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  

[5 rows x 34 columns]

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17031 entries, 0 to 17030
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   post_id                     17031 non-null  int64  
 1   Loại tin                    17031 non-null  object 
 2   Tiêu đề                     17031 non-null  object 
 3   Giá                         17031 non-null  object 
 4   Diện tích                   17031 non-null  object 
 5   Địa chỉ                     17031 non-null  object 
 6   Giá/m2                      8790 non-null   object 
 7   Giấy tờ pháp lý             9112 non-null   object 
 8   Loại hình đất               3514 non-null   object 
 9   Mô tả                       17031 non-null  object 
 10  URL                         17031 non-null  object 
 11  date                        17031 non-null  object 
 12  Liên hệ                     17013 non-null  object 
 13  card_visit                  170

In [77]:
df.shape

(17031, 34)

# Function

In [78]:
def replace_empty_with_nan(text):
    return np.nan if text.strip() == '' else text

# Loại tin

In [79]:
df['Loại tin'].unique()

array(['Mua bán', 'Cho thuê'], dtype=object)

# Diện tích

In [80]:
# df['Diện tích'].unique()

In [81]:
def clean_size(i):
    if isinstance(i, str):
        # Remove ' m²'
        return i.replace(' m²','').replace(' m2','')
    else:
        return ''

In [82]:
df['Diện tích'] = df['Diện tích'].apply(clean_size)

In [83]:
df['Diện tích'] = df['Diện tích'].apply(replace_empty_with_nan)

In [84]:
df['Diện tích']=df['Diện tích'].astype(float)

# Giá 

In [85]:
# df['Giá'].unique()

In [86]:
# df['Giá'][df['Loại tin']=='Mua bán'].unique()

In [87]:
# df['Giá'][df['Loại tin']=='Cho thuê'].unique()

In [88]:
df['Giá'] = df['Giá'].apply(lambda x: x.replace('.','').replace(',', '.'))

In [89]:
def clean_price(x, dien_tich):
    if 'đ/tháng' in x:
        return float(x.split()[0]) 
    elif 'triệu/tháng' in x:
        return float(x.split()[0]) * 1000000
    elif 'tỷ/tháng' in x:
        return float(x.split()[0]) * 1000000000
    elif ' tỷ' in x:
        return float(x.split()[0]) * 1000000000
    elif ' triệu' in x:
        return float(x.split()[0]) * 1000000
    elif ' đ' in x:
        return float(x.split()[0])
    elif x == 'Thỏa thuận':
        return None  
    else:
        return x

In [90]:
df['Giá'] = df.apply(lambda row: clean_price(row['Giá'], row['Diện tích']), axis=1)

In [91]:
df['Giá']=df['Giá'].astype(float)

# Giá/m2

In [92]:
df['Giá/m2'].unique()

array([' 237.500 đ/m²', ' 32,8 triệu/m²', ' 35,36 triệu/m²', ...,
       ' 4,1 triệu/m²', ' 25,95 triệu/m²', ' 106 triệu/m²'], dtype=object)

In [93]:
df['Giá/m2'] = df['Giá/m2'].apply(lambda x: str(x).replace('.', '').replace(',', '.').replace('m2','m²'))

In [94]:
def clean_price(x):
    if 'đ/m²' in x:
        return float(x.split()[0]) 
    elif 'triệu/m²' in x:
        return float(x.split()[0]) * 1000000
    elif 'tỷ/m²' in x:
        return float(x.split()[0]) * 1000000000
    elif x == 'Thỏa thuận':
        return None  
    else:
        return x

In [95]:
df['Giá/m2']=df['Giá/m2'].apply(clean_price)

In [96]:
df['Giá/m2']=df['Giá/m2'].astype(float)

# Giấy tờ pháp lý

In [97]:
df['Giấy tờ pháp lý'].unique()

array([' Đã có sổ', nan, ' Đang chờ sổ', ' Giấy tờ khác'], dtype=object)

In [98]:
df['Giấy tờ pháp lý']=df['Giấy tờ pháp lý'].str.strip()

# Loại hình đất, loại hình căn hộ, loại hình văn phòng, loại hình nhà ở

In [99]:
df['Loại hình đất'].unique()

array([' Đất nông nghiệp', ' Đất thổ cư', nan, ' Đất nền dự án',
       ' Đất công nghiệp'], dtype=object)

In [100]:
df['Loại hình căn hộ'].unique()

array([nan, ' Chung cư', ' Căn hộ dịch vụ, mini', ' Duplex', ' Officetel',
       ' Penthouse', ' Tập thể, cư xá'], dtype=object)

In [101]:
df['Loại hình văn phòng'].unique()

array([nan, ' Mặt bằng kinh doanh', ' Shophouse', ' Văn phòng',
       ' Officetel'], dtype=object)

In [102]:
df['Loại hình nhà ở'].unique()

array([nan, ' Nhà ngõ, hẻm', ' Nhà mặt phố, mặt tiền', ' Nhà biệt thự',
       ' Nhà phố liền kề'], dtype=object)

In [103]:
df['Loại hình đất']=df['Loại hình đất'].str.strip()
df['Loại hình căn hộ']=df['Loại hình căn hộ'].str.strip()
df['Loại hình văn phòng']=df['Loại hình văn phòng'].str.strip()
df['Loại hình nhà ở']=df['Loại hình nhà ở'].str.strip()

# date

In [104]:
df['date'].unique()

array(['2023-09-24', '2023-09-25', '2023-09-26', '2023-09-27',
       '2023-10-02', '2023-10-03', '2023-10-04', '2023-10-05',
       '2023-10-09', '2023-10-10', '2023-10-12', '2023-10-13'],
      dtype=object)

# Liên hệ

In [105]:
df['Liên hệ'].unique()

array(['Minh Phương Phát', 'Quốc Huỳnh', 'Anh Tân', ...,
       'Bùi Thị Mỹ Duyên', 'Alo', 'Cho Thuê Nhà Chính Chủ'], dtype=object)

In [106]:
df['Liên hệ']=df['Liên hệ'].str.title()

# Hướng cửa chính, hướng ban công

In [107]:
df['Hướng cửa chính'].unique()

array([nan, ' Tây Nam', ' Tây', ' Tây Bắc', ' Đông Bắc', ' Đông Nam',
       ' Bắc', ' Nam', ' Đông'], dtype=object)

In [108]:
df['Hướng ban công'].unique()

array([nan, ' Đông Bắc', ' Tây Bắc', ' Đông', ' Tây', ' Đông Nam',
       ' Tây Nam', ' Bắc', ' Nam'], dtype=object)

In [109]:
df['Hướng cửa chính']=df['Hướng cửa chính'].str.strip()
df['Hướng ban công']=df['Hướng ban công'].str.strip()

# Chiều ngang, chiều dài, diện tích sử dụng

In [110]:
# df['Chiều ngang'].unique()

In [111]:
# df['Chiều dài'].unique()

In [112]:
# df['Diện tích sử dụng'].unique()

In [113]:
df['Chiều ngang']=df['Chiều ngang'].apply(lambda x: float(str(x).split()[0]))
df['Chiều dài']=df['Chiều dài'].apply(lambda x: float(str(x).split()[0]))
df['Diện tích sử dụng']=df['Diện tích sử dụng'].apply(lambda x: float(str(x).split()[0]))

# Đặt điểm nhà/đất

In [114]:
df['Đặc điểm nhà/đất'].unique()

array([nan, ' Mặt tiền', ' Hẻm xe hơi', ' Nở hậu', ' Hẻm xe hơi,Nở hậu',
       ' Mặt tiền,Nở hậu', ' Hẻm xe hơi,Nở hậu,Mặt tiền',
       ' Nở hậu,Hẻm xe hơi', ' Mặt tiền,Hẻm xe hơi,Nở hậu',
       ' Mặt tiền,Nở hậu,Hẻm xe hơi', ' Hẻm xe hơi,Mặt tiền',
       ' Nở hậu,Mặt tiền', ' Mặt tiền,Hẻm xe hơi',
       ' Nở hậu,Mặt tiền,Hẻm xe hơi', ' 1', ' Hẻm xe hơi,Mặt tiền,Nở hậu',
       ' Nở hậu,Hẻm xe hơi,Mặt tiền'], dtype=object)

In [115]:
df['Đặc điểm nhà/đất']=df['Đặc điểm nhà/đất'].str.strip()

In [116]:
def replace_f(text):
    if isinstance(text, str):
        text = text.strip().lower()
        if ('hẻm xe hơi' in text) and ('nở hậu' in text) and ('mặt tiền' in text):
            return 'Mặt tiền, Hẻm xe hơi, Nở hậu'
        elif ('hẻm xe hơi' in text) and ('nở hậu' in text):
            return 'Hẻm xe hơi, Nở hậu'
        elif ('hẻm xe hơi' in text)  and ('mặt tiền' in text):
            return 'Mặt tiền, Hẻm xe hơi'
        elif ('nở hậu' in text) and ('mặt tiền' in text):
            return 'Mặt tiền, Nở hậu'
        elif ('hẻm xe hơi' in text):
            return 'Hẻm xe hơi'
        elif ('nở hậu' in text):
            return 'Nở hậu'
        elif ('mặt tiền' in text):
            return 'Mặt tiền'
        else:
            return text
    else:
        return text

In [117]:
df['Đặc điểm nhà/đất']=df['Đặc điểm nhà/đất'].apply(replace_f)

# Số phòng ngủ, Số phòng vệ sinh

In [118]:
df['Số phòng ngủ'].unique()

array([nan, ' 3 phòng', ' nhiều hơn 10 phòng', ' 5 phòng', ' 6 phòng',
       ' 1 phòng', ' 2 phòng', ' 4 phòng', ' 7 phòng', ' 8 phòng',
       ' 9 phòng', ' 10 phòng'], dtype=object)

In [119]:
df['Số phòng vệ sinh'].unique()

array([nan, ' 3 phòng', ' 2 phòng', ' Nhiều hơn 6 phòng', ' 6 phòng',
       ' 1 phòng', ' 4 phòng', ' 5 phòng'], dtype=object)

In [120]:
def replace_r(text):
    if isinstance(text, str):
        text = text.strip().lower()
        if 'nhiều hơn' in text:
            return text
        else:
            return text.split()[0]
    else:
        return text

In [121]:
df['Số phòng ngủ']=df['Số phòng ngủ'].apply(replace_r)
df['Số phòng vệ sinh']=df['Số phòng vệ sinh'].apply(replace_r)

# Tổng số tầng, tầng số

In [122]:
df['Tổng số tầng'].unique()

array([ nan,   2.,   3.,   1.,   4.,   5.,  10.,   6.,   8.,   7.,  14.,
        11.,  35.,  15.,  22.,   9.,  20.,  33.,  23., 275.])

In [123]:
df['Tầng số'].unique()

array([ nan,   9.,   2.,   8.,   6.,   7.,   4.,  34.,  23.,   3.,  18.,
        10.,  28.,  16.,  15.,  11.,  14.,   5.,  12.,  29.,  25.,   1.,
        20.,  17.,  31.,  27.,  26.,  30.,  13.,  19.,  21.,  22.,  36.,
        33.,  40.,  35.,  38.,  44.,  55.,  39.,  24., 810., 963.])

# Tình trạng nội thất, tình trạng bất động sản

In [124]:
df['Tình trạng nội thất'].unique()

array([nan, ' Nội thất cao cấp', ' Nội thất đầy đủ', ' Bàn giao thô',
       ' Nhà trống'], dtype=object)

In [125]:
df['Tình trạng nội thất']=df['Tình trạng nội thất'].str.strip()

In [126]:
df['Tình trạng nội thất']=df['Tình trạng nội thất'].apply(lambda x: str(x).replace('Nhà trống', 'Không nội thất'))

In [127]:
df['Tình trạng bất động sản'].unique()

array([nan, ' Chưa bàn giao', ' Đã bàn giao'], dtype=object)

In [128]:
df['Tình trạng bất động sản']=df['Tình trạng bất động sản'].str.strip()

# Mã căn, mã lô

In [129]:
df['Mã căn'].unique()

array([nan, ' 205', ' 9999', ' 8888', ' 1', ' 10', ' 12', ' 38',
       ' P2-16.13', ' V1', ' 0905271165', ' P2-07.08', ' 250', ' 05',
       ' 2903', ' 904', ' P2-13.16', ' P2-03.12', ' 1606', ' 2105',
       ' P2-07.12', ' 11', ' 2607', ' P103A09', ' P10515', ' 75', ' CT10',
       ' 407', ' 140', ' 608', ' 6B06', ' 616', ' DNPlaza3beds', ' 301',
       ' VL1', ' 03', ' 101', ' 27', ' 08', ' 02', ' 302', ' 401', ' 402',
       ' 114', ' 24', ' ABC', ' 20', ' 06', ' 15', ' 11CT02',
       ' 623 nguyen tat thanh', ' 4004', ' 04', ' A301', ' 202', ' 168',
       ' 01', ' 09', ' CT10-CH01.07', ' CTO2', ' CH-07-07', ' P208-07',
       ' 11A08', ' B3-21-11', ' 12A05', ' k218', ' 3', ' P21508', ' 4B',
       ' P1508', ' B2.50', ' 17', ' NNC0738', ' NNC0737', ' NNC0736',
       ' NNC0735', ' JH02', ' P210-02', ' P2-10.09', ' P2-09.08',
       ' TN0079', ' S14'], dtype=object)

In [130]:
df['Mã lô'].unique()

array([nan, ' 1111', ' 8888', ' 27', ' 16', ' B2.124', ' B3.36',
       ' B2.134', ' B2.41', ' 12', ' 46', ' 168', ' 38', ' 18', ' 15',
       ' 90', ' 213', ' B2A-10', ' E', ' B1', ' 356', ' 47', ' 68',
       ' B2.88', ' NCL', ' 32', ' 48', ' 118', ' B5-15x', ' b1-1 -38',
       ' Can ban lo dat 5x25', ' 7', ' 33 36', ' 21 Khu B2 40', ' 53',
       ' 34-B2.3', ' 94', ' 1x', ' 1', ' 110', ' 59', ' 120', ' 1458',
       ' 702', ' 0983611388', ' 467'], dtype=object)

In [131]:
df['Mã căn']=df['Mã căn'].str.strip()
df['Mã lô']=df['Mã lô'].str.strip()

# Đặc điểm căn hộ

In [132]:
df['Đặc điểm căn hộ'].unique()

array([nan, ' Căn góc'], dtype=object)

In [133]:
df['Đặc điểm căn hộ']=df['Đặc điểm căn hộ'].str.strip()

# Số tiền cọc

In [134]:
# df['Số tiền cọc'].unique()

In [135]:
df['Số tiền cọc']=df['Số tiền cọc'].apply( lambda x: float(str(x).strip().replace('.','').split()[0]))

# Mô tả

In [136]:
df['Mô tả'].unique()

array(['💥💥💥Đất rộng lại giá tốt 40.000m có sẵn vườn cây ăn quả, đất có sẵn nhà tiền chế kiên cố khoảng 300m2,hàng rào lưới b40, đèn năng lượng bắt quanh vườn.\n💥💥💥Đường bê tông kiên cố\nTường rào cổng nhà xây sẵn đất 3 mặt tiền\n🌹🌹🌹Vị trí hoà ninh không quy hoạch\ncách ubnd cách chợ trường học chỉ 1km,cách Bà nà hills chỉ 4km\nDi chuyển về tttp Đà Nẵng chỉ có 15km\nHình ảnh thực tế của lô đất\nLH. *** Minh Phương Phát',
       '+ Bán đất số 21 Đỗ Nhuận, khu Trung Nghĩa, phường Hòa Minh, DTĐ: 250m². Đường 5m5 lề 3m, ô tô đậu thoải mái.\n\n+ Khu dân cư trí thức, yên tĩnh, phù hợp để làm nhà ở.\n\n+ Hướng Tây Nam.\n+ Ngân hàng hỗ trợ vay 6 tỷ.\n\nGiá bán: 8.2 tỷ, thương lượng.',
       'Bán nhà kiệt 82 Nguyễn Văn Linh, hẻm 3m5, cách đường Nguyễn Văn Linh khoảng 100 m.\nVị trí đẹp ngay trung tâm thành phố. DTĐ: 140m², Chiều ngang 7m, DTSD: 110m². Lô đất rất giá trị, rất khó tìm lô đất tương tự ở ngay trung tâm thành phố!\n\nNhà gồm 3PN, 3WC, nhà đẹp, sạch sẽ. Hướng chính Tây.\n\nGiá: 4.95 

# Rename columns

In [137]:
df.columns

Index(['post_id', 'Loại tin', 'Tiêu đề', 'Giá', 'Diện tích', 'Địa chỉ',
       'Giá/m2', 'Giấy tờ pháp lý', 'Loại hình đất', 'Mô tả', 'URL', 'date',
       'Liên hệ', 'card_visit', 'Hướng cửa chính', 'Chiều ngang', 'Chiều dài',
       'Đặc điểm nhà/đất', 'Số phòng ngủ', 'Số phòng vệ sinh',
       'Loại hình nhà ở', 'Diện tích sử dụng', 'Tổng số tầng',
       'Tình trạng nội thất', 'Tên phân khu/Lô/Block/Tháp',
       'Tình trạng bất động sản', 'Tầng số', 'Hướng ban công',
       'Loại hình căn hộ', 'Loại hình văn phòng', 'Mã căn', 'Đặc điểm căn hộ',
       'Mã lô', 'Số tiền cọc'],
      dtype='object')

In [138]:
df=df.rename(columns={'Giấy tờ pháp lý':'Pháp lý','Liên hệ':'Tên người dùng','date':'Ngày crawl',
                      'Tình trạng nội thất':'Nội thất','Số phòng vệ sinh':'Số toilet','Hướng cửa chính':'Hướng nhà'})

# Save data

In [139]:
df

post_id  Loại tin                                            Tiêu đề  \
0      110154174   Mua bán  Bán 4ha đất vườn sổ đỏ có sẳn trang trại nhà v...   
1      102957944   Mua bán  Bán đất 21 Đỗ Nhuận, dt: 250m2, ngang 8m, nở h...   
2      108055434   Mua bán  Bán nhà hẻm 3m5 Nguyễn Văn Linh, 140m2 đất, ng...   
3      102942264   Mua bán  Bán đất hẻm 3m 59/31 Núi Thành, 162m2, 4.25 tỷ...   
4      110181789   Mua bán  Nhà 2 tầng 2 mặt kiệt ngay biển Nguyễn Tất Thà...   
...          ...       ...                                                ...   
17026  110711513  Cho thuê  3 MB SIÊU PHẨM sàn đẹp tại đường đắc địa bậc n...   
17027  110711497  Cho thuê    CĂN HỘ SANG TRỌNG GẦN CẦU THUẬN PHƯỚC - SƠN TRÀ   
17028  110711465  Cho thuê  NHÀ 3.5 TẦNG MT ĐƯỜNG MAI AM - CÓ NỘI THẤT - H...   
17029  110711449  Cho thuê    📍 CHO THUÊ NHÀ 2 MẶT TIỀN HOÀNG DIỆU NGANG 6,5M   
17030  110711234  Cho thuê  CHO THUÊ NHÀ NGUYÊN CĂN ,ĐỐI DIỆN CỔNG CHỢ CẨM LỆ   

                Giá  Diện tích  \
0      9.500000e+09    40000.0   
1      8.200000e+09      250.0   
2      4.950000e+09      140.0   
3      4.250000e+09      162.0   
4      2.950000e+09       62.0   
...             ...        ...   
17026  4.500000e+07      432.0   
17027  5.000000e+06       35.0   
17028  1.100000e+07      135.0   
17029  2.000000e+07      200.0   
17030  1.350000e+07      100.0   

                                                 Địa chỉ      Giá/m2  \
0           DT 602, Xã Hòa Ninh, Huyện Hòa Vang, Đà Nẵng    237500.0   
1      21, Đường Đỗ Nhuận, Phường Hòa Minh, Quận Liên...  32800000.0   
2      K82/H10/36, Nguyễn văn linh, Phường Nam Dương,...  35360000.0   
3      Kiệt 59 Núi Thành, Phường Bình Hiên, Quận Hải ...  26230000.0   
4      K1/20, Tôn Thất Đạm, Phường Xuân Hà, Quận Than...  47580000.0   
...                                                  ...         ...   
17026  Nguyễn Văn Linh, Phường Vĩnh Trung, Quận Thanh...         NaN   
17027  Trần Sâm, Phường Nại Hiên Đông, Quận Sơn Trà, ...         NaN   
17028  Mai Am, Phường Thuận Phước, Quận Hải Châu, Đà ...         NaN   
17029  Hoàng Diệu, Phường Bình Thuận, Quận Hải Châu, ...         NaN   
17030  50, ĐẶNG VĂN NGỮ, Phường Khuê Trung, Quận Cẩm ...         NaN   

        Pháp lý    Loại hình đất  \
0      Đã có sổ  Đất nông nghiệp   
1      Đã có sổ       Đất thổ cư   
2      Đã có sổ              NaN   
3           NaN       Đất thổ cư   
4      Đã có sổ              NaN   
...         ...              ...   
17026       NaN              NaN   
17027       NaN              NaN   
17028       NaN              NaN   
17029       NaN              NaN   
17030  Đã có sổ              NaN   

                                                   Mô tả  ...  \
0      💥💥💥Đất rộng lại giá tốt 40.000m có sẵn vườn câ...  ...   
1      + Bán đất số 21 Đỗ Nhuận, khu Trung Nghĩa, phư...  ...   
2      Bán nhà kiệt 82 Nguyễn Văn Linh, hẻm 3m5, cách...  ...   
3      Bán đất hẻm 3m số 59/31 Núi Thành, cách đường ...  ...   
4      Tôi là chính chủ cần bán nhà tại địa chỉ K1/20...  ...   
...                                                  ...  ...   
17026  MB số 1\nDiện tích: 405m2 - 4 tầng\nBề ngang: ...  ...   
17027  CĂN HỘ SANG TRỌNG GẦN CẦU THUẬN PHƯỚC - SƠN TR...  ...   
17028  🏫𝐂𝐡𝐨 𝐓𝐡𝐮𝐞̂ 𝐍𝐡𝐚̀ 𝟑,𝟓 𝐓𝐚̂̀𝐧𝐠 𝐌𝐚̣̆𝐭 𝐓𝐢𝐞̂̀𝐧 𝐌𝐚𝐢 𝐀𝐦...  ...   
17029  📍 CHO THUÊ NHÀ 2 MẶT TIỀN HOÀNG DIỆU NGANG 6,5...  ...   
17030  CHO THUÊ NHÀ NGUYÊN CĂN MẶT TIỀN CỔNG CHỢ CẨM ...  ...   

      Tên phân khu/Lô/Block/Tháp Tình trạng bất động sản Tầng số  \
0                            NaN                     NaN     NaN   
1                            NaN                     NaN     NaN   
2                            NaN                     NaN     NaN   
3                            NaN                     NaN     NaN   
4                            NaN                     NaN     NaN   
...                          ...                     ...     ...   
17026                        NaN                     NaN     NaN   
1702

In [140]:
df.to_excel('nt.xlsx')
df.to_csv('nt.csv')